# Generated by Django 5.0.3 on 2024-03-14 06:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('income_range', models.CharField(choices=[('<5', 'Up to ₹5 lac'), ('5-10', '₹5 - ₹10 lac'), ('10-20', '₹10 - ₹20 lac'), ('20-50', '₹20 - ₹50 lac'), ('50-100', '₹50 - ₹1 crore'), ('>100', 'Over ₹1 crore')], max_length=200)),
                ('type_of_employment', models.CharField(max_length=200)),
                ('aadhar_number', models.CharField(blank=True, max_length=200, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=200, null=True)),
                ('aadhar_image', models.URLField(blank=True, max_length=500, null=True)),
                ('pan_image', models.URLField(blank=True, max_length=500, null=True)),
                ('face_image', models.URLField(blank=True, max_length=500, null=True)),
                ('signature_image', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
