# Generated by Django 5.0.3 on 2024-03-14 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('identities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identities.identity'),
        ),
    ]
